"options":
  "san-ip":
    "type": "string"
    "description": "IP address of SAN controller for SSH access to the array"
    "default": !!null ""
  "san-login":
    "type": "string"
    "description": "Username for SAN controller for SSH access to the array"
    "default": !!null ""
  "san-password":
    "type": "string"
    "description": "Password for SAN controller for SSH access to the array"
    "default": !!null ""
  "hpe3par-username":
    "type": "string"
    "description": "3PAR username with the 'edit' role"
    "default": !!null ""
  "hpe3par-password":
    "type": "string"
    "description": "3PAR password for the user specified in hpe3par_username"
    "default": !!null ""
  "hpe3par-api-url":
    "type": "string"
    "description": "3PAR WS API Server URL"
    "default": !!null ""
  "hpe3par-cpg":
    "type": "string"
    "description": "3PAR CPG to use for volume creation"
    "default": !!null ""
  "volume-backend-name":
    "type": "string"
    "description": "Name to present to cinder, leave blank to use charm (or alias)\
      \ name"
    "default": !!null ""
